name: nonoflex_alpha
description: 노노유통의 재고관리 시스템

# 버전 정보
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.24.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  logger: ^1.1.0
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

#  # firebase
#  firebase_core: ^1.23.0

  # flutter _ gen
  # flutter packages pub run build_runner build
  build_runner: 2.1.2
  flutter_gen_runner: 4.3.0

  # hive:
  hive: ^2.2.3

  # http
  http: ^0.13.5

  # provider
  provider: ^6.0.3

  # get
  get: 4.6.0

  # path_provider
  path_provider: ^2.0.11

  # qr_code
  qr_flutter: ^4.0.0

#  # toast
#  fluttertoast: ^8.0.9

  # get it (DI)
  get_it: 7.2.0

flutter_gen:

  # Color pallet
  colors:
    inputs:
      - assets/color/color_light.xml

flutter:
  uses-material-design: true
  # asset
  assets:
    - assets/images/
    - assets/images/logo/

  # fonts
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf