name: nonoflex_alpha
description: 노노유통의 재고관리 시스템

# 버전 정보
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.1.0

  # toast
  fluttertoast: ^8.1.1

  # intl
  intl: ^0.17.0

  # http
  http: ^0.13.5

  # QR Code 스캔
  qr_code_scanner: ^1.0.1

  # QR Code 생성
#  pretty_qr_code: ^2.0.3
#  qr_flutter: ^4.0.0
  barcode_widget: ^2.0.3

  # image
  cached_network_image: ^3.2.3

  # image picker
  image_picker: ^0.8.6

  # hive DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  # get
  get: 4.6.5

  # get it (DI)
  get_it: 7.2.0

  # provider
  provider: ^6.0.3

  # path_provider
  path_provider: ^2.0.11

  # mockito
  mockito: ^5.3.2

  # logger
  logger: ^1.1.0

  package_info_plus: ^3.0.2

  # qr_code
  #  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # flutter _ gen
  # flutter packages pub run build_runner build
  build_runner: 2.3.2
  flutter_gen_runner: 5.0.3

flutter_gen:

  # Color pallet
  colors:
    inputs:
      - assets/color/color_light.xml

flutter:
  uses-material-design: true
  # assets
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/icons/

  # fonts
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Thin.otf